services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=giftcard'
      - 'POSTGRES_PASSWORD=Giftcard*123!'
      - 'POSTGRES_USER=giftcard'
    ports:
      - '5432:5432'

  kafka:
    image: 'apache/kafka:3.8.0'
    ports:
      - '9092:9092'