services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=giftcard'
      - 'POSTGRES_PASSWORD=Giftcard*123!'
      - 'POSTGRES_USER=giftcard'
    ports:
      - '5432:5432'

  kafka:
    image: 'apache/kafka:3.8.0'
    ports:
      - '9092:9092'

  prometheus:
    image: 'prom/prometheus:v3.1.0'
    container_name: 'prometheus'
    restart: 'unless-stopped'
    volumes:
      - './observability/prometheus/config:/etc/prometheus/'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'

  grafana:
    image: 'grafana/grafana-oss:11.5.1'
    container_name: 'grafana'
    restart: 'unless-stopped'
    volumes:
      - './observability/grafana:/var/lib/grafana'
    ports:
      - '3000:3000'
    links:
      - 'prometheus:prometheus'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=admin'
      - 'GF_USERS_ALLOW_SIGN_UP=false'
      - 'GF_SERVER_DOMAIN=localhost'